import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { StoreProvider } from "@/slices/StoreProvider";

const myFont = localFont({ src: '../fonts/PPNeueMachina-Regular.otf'})

export const metadata: Metadata = {
  title: "Portfolio Overview",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <StoreProvider>
          <body
              className={myFont.className}
          >
                {children}
          </body>
        </StoreProvider>
      </html>
  );
}